### ISSUE TITLE
SFC support

### ISSUE THREAD

**Issue by rndmerle** [liximomo/vue-function-api#12]
Hello and thanks for your work.

I was wondering about the SFC support. Currently it seems there is a binding issue (`Property or method "msg" is not defined on the instance but referenced during render`).
I tested with:
```
<template>
  <h1>{{ msg }}</h1>
</template>

<script lang="ts">
import Vue from "vue";
import { value } from "vue-function-api";

export default Vue.extend({
  setup() {
    const msg = value("Hello World!");

    return { msg };
  }
});
</script>
```

**Comment by parker-codes** [comment]
@rndmerle I am not having this issue. Did you bind the plugin with Vue.use()?

**Comment by rndmerle** [comment]
Sorry my bad. I can't believe I missed the plugin :(
