### ISSUE TITLE
用ts的时候vue的一些其他属性暂未支持

### ISSUE THREAD

**Issue by pangao66** [liximomo/vue-function-api#8]
![image](https://user-images.githubusercontent.com/20113031/59993710-d3cfbd80-9683-11e9-9ee3-a9c327bb15a5.png)
https://github.com/vuejs/rfcs/blob/function-apis/active-rfcs/0000-function-api.md
ref,emit等, 目前能用this.xxx的写法,但是如果用ts格式是会报错的, 3.0的rfcs会传递个setup参数
![image](https://user-images.githubusercontent.com/20113031/59993827-3b860880-9684-11e9-8ff9-37e70177a9d4.png)
props的类型推导暂未支持

**Comment by liximomo** [comment]
context 的 api 目前不是很明确，还需要等尤大给出更具体的 api 才可以实现。

**Comment by antfu** [comment]
@liximomo 是否可以考虑按照现有的范例将现有api的this包装成context呢？

**Comment by liximomo** [comment]
升级到2.x

Anthony Fu <notifications@github.com> 于 2019年6月24日周一 18:38写道：

**Comment by pangao66** [comment]
Context是不没有导出,
![image](https://user-images.githubusercontent.com/20113031/60073005-d0a30300-9751-11e9-9603-4e75a47cc709.png)
使用context也是无法正常使用的
 console.log(context)
![image](https://user-images.githubusercontent.com/20113031/60072944-a6514580-9751-11e9-8457-14e1a01fb8f6.png)
也都是这样的,都是undefined

**Comment by liximomo** [comment]
为什么需要导出Context？

**Comment by pangao66** [comment]
![image](https://user-images.githubusercontent.com/20113031/60075292-89b80c00-9757-11e9-9e6f-c2da472bacea.png)
写ts的时候,Context作为interface

**Comment by liximomo** [comment]
`setup(props, context)`就足够了，可以自动推导出 context 的类型。

**Comment by pangao66** [comment]
```js  
setup(props, context) {
    const handleClick = () => {
      context.emit('send')
    }
    // watch
    return {
      handleClick
    }
  }
```
目前这样写是会无法使用的,
会报错
[Vue warn]: Error in v-on handler: "TypeError: context.emit is not a function"
版本2.0.4

**Comment by liximomo** [comment]
鼠标悬停 `context` 然我看看提示的是什么类型？

**Comment by pangao66** [comment]
![image](https://user-images.githubusercontent.com/20113031/60076402-0ba93480-975a-11e9-9acb-5ffbec916453.png)

类型是Context,也能输出,但是里面的字属性是undefined
console.log(context) 如下:
![image](https://user-images.githubusercontent.com/20113031/60076447-31ced480-975a-11e9-8428-da0e6ec9fc8e.png)

**Comment by liximomo** [comment]
这和类型没关系，这是因为值没有正确被代理到 context. 我修复一下

**Comment by liximomo** [comment]
@pangao66 升级到 2.0.5

**Comment by pangao66** [comment]
非常感谢
